# PostgreSQL database configuration

connection: &connection
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: aleksa
  password:
  timeout: 5000

development:
  <<: *connection
  database: rails_development

test:
  <<: *connection
  database: rails_test
